-- Curated exercise library — the ONLY pool the AI may recommend from.
-- Applied via: supabase db push --include-seed  (or paste into SQL editor)

insert into public.exercise_library
  (slug, name, category, target_areas, instructions_md, evidence_level) values
('eccentric-calf-raises', 'Eccentric Calf Raises', 'strength',
 '{calf,achilles}',
 'Stand on a step, rise up on both feet, shift to one leg and lower slowly over 3–5 seconds. 3×15 per side after easy runs.',
 'strong'),
('calf-stretch-wall', 'Wall Calf Stretch', 'stretch',
 '{calf}',
 'Hands on a wall, one leg back with heel down. Hold 2 min per side, knee straight (gastroc) then slightly bent (soleus). Best while warm after a run.',
 'moderate'),
('foam-roll-calves', 'Foam Roll Calves', 'foam_roll',
 '{calf}',
 'Roll slowly from ankle to knee, pausing 20–30s on tender spots. 2 min per side post-run.',
 'moderate'),
('nordic-hamstring', 'Nordic Hamstring Lowers', 'strength',
 '{hamstring}',
 'Kneel with ankles anchored, lower your torso forward as slowly as possible. 3×5, twice weekly.',
 'strong'),
('glute-bridge', 'Single-Leg Glute Bridge', 'strength',
 '{glute,hip}',
 'On your back, one foot planted, drive hips up through the heel. 3×12 per side.',
 'moderate'),
('side-plank-hip', 'Side Plank with Leg Lift', 'strength',
 '{hip,glute,core}',
 'Side plank on the elbow; slowly raise and lower the top leg. 3×10 per side. Key for hip-drop patterns.',
 'strong'),
('hip-flexor-stretch', 'Half-Kneeling Hip Flexor Stretch', 'stretch',
 '{hip,quad}',
 'Half-kneel, tuck the pelvis, shift weight forward until you feel the front of the hip. 90s per side.',
 'moderate'),
('clamshells', 'Banded Clamshells', 'pt',
 '{hip,glute}',
 'Side-lying with a band above the knees, heels together, open the top knee. 3×15 per side.',
 'moderate'),
('ankle-mobility', 'Ankle Wall Mobilizations', 'mobility',
 '{ankle,calf}',
 'Foot ~4 inches from a wall, drive the knee over the toes without lifting the heel. 2×10 per side.',
 'moderate'),
('it-band-roll', 'Foam Roll Lateral Thigh', 'foam_roll',
 '{it band,quad}',
 'Roll the outer thigh from hip to knee, slowly, 90s per side. Pair with side-plank work.',
 'weak'),
('a-skips', 'A-Skips', 'drill',
 '{form,cadence}',
 '2×30m before quality sessions: rhythmic skipping with tall posture and quick ground contact. Reinforces cadence and footstrike under the hips.',
 'moderate'),
('high-knees-drill', 'High Knees', 'drill',
 '{form,cadence}',
 '2×20m: quick, light steps with knees driving to hip height, arms at 90°. Warm-up drill for turnover.',
 'moderate')
on conflict (slug) do nothing;
